image: /home/vboxuser/GPS_conversion/Glanderson_costmap_clean.pgm
resolution: 0.1  # Meters per pixel
origin: [-100.0, -100.0, 0.0]  # The origin of the map [x, y, yaw] in meters and radians
occupied_thresh: 0.65
free_thresh: 0.196
negate: 0

